[package]
name = "rust_gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libadwaita = "0.1.1"
gtk4 = "0.4.7"
gio = "0.15.11"
